version: 2
updates:
- package-ecosystem: npm
  directory: "/howmanypeoplearethereinthe.world"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - ">= 11.a, < 12"
  - dependency-name: "@types/node"
    versions:
    - ">= 13.a, < 14"
  - dependency-name: "@types/node"
    versions:
    - ">= 14.a, < 15"
  - dependency-name: "@types/node"
    versions:
    - 15.0.0
